Fix merge queue tests-passed check logic (#3306)

diff --git a/.github/workflows/merge_group.yml b/.github/workflows/merge_group.yml
--- a/.github/workflows/merge_group.yml
+++ b/.github/workflows/merge_group.yml
@@ -53,6 +53,12 @@ jobs:
 
   tests-passed:
     needs: [call-ci, call-hexagon, call-xtensa-presubmit, call-cortex-m, call-cortex-m-armclang, call-riscv-postmerge, call-xtensa-postmerge]
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - run: exit 0
+      - run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more dependent jobs failed."
+            exit 1
+          fi
+          exit 0
