move pr has BUG= check into tests_entry.yml (#1498)
* move pr has BUG= check into tests_entry.yml

* reverting workflow calls to needs ci-run

diff --git a/.github/workflows/tests_entry.yml b/.github/workflows/tests_entry.yml
--- a/.github/workflows/tests_entry.yml
+++ b/.github/workflows/tests_entry.yml
@@ -2,6 +2,7 @@
 # Entry point to the test suites
 #
 # - If neither ci:run or ci:ready_to_merge labels are on PR, fail and exit.
+# - If the PR comment body doesn't contain 'BUG=' fail and exit.
 # - If ci:run label is on PR, remove ci:run, run the test scripts.
 # - If ci:ready_to_merge is on the PR and the pull_request_target type is synchronize not triggered
 #   by the mergify[bot] user, remove label and fail job.
@@ -69,6 +70,18 @@ jobs:
               repo: context.repo.repo,
               name: 'ci:run'
             })
+
+  pr-has-bug:
+    runs-on: ubuntu-latest
+    needs: ci-run
+    name: PR has Bug
+    steps:
+      - name: Check for BUG=
+        if: ${{ !contains(github.event.pull_request.body, 'BUG=') }}
+        run: |
+          echo "PR description requires a BUG= line with issue number."
+          echo "See https://testing.googleblog.com/2017/09/code-health-providing-context-with.html for additional context"
+          exit 1
   
   call-ci:
     needs: ci-run
